/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosSeoRouteImport } from './routes/servicios.seo'
import { Route as ServiciosDisenoWebRouteImport } from './routes/servicios.diseno-web'
import { Route as ProyectosVoltiaruralRouteImport } from './routes/proyectos.voltiarural'
import { Route as ProyectosSolaraRouteImport } from './routes/proyectos.solara'
import { Route as ProyectosIchoRouteImport } from './routes/proyectos.icho'
import { Route as ProyectosFdcFontaneroRouteImport } from './routes/proyectos.fdc-fontanero'

const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSeoRoute = ServiciosSeoRouteImport.update({
  id: '/servicios/seo',
  path: '/servicios/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosDisenoWebRoute = ServiciosDisenoWebRouteImport.update({
  id: '/servicios/diseno-web',
  path: '/servicios/diseno-web',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosVoltiaruralRoute = ProyectosVoltiaruralRouteImport.update({
  id: '/proyectos/voltiarural',
  path: '/proyectos/voltiarural',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosSolaraRoute = ProyectosSolaraRouteImport.update({
  id: '/proyectos/solara',
  path: '/proyectos/solara',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIchoRoute = ProyectosIchoRouteImport.update({
  id: '/proyectos/icho',
  path: '/proyectos/icho',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosFdcFontaneroRoute = ProyectosFdcFontaneroRouteImport.update({
  id: '/proyectos/fdc-fontanero',
  path: '/proyectos/fdc-fontanero',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/proyectos/fdc-fontanero': typeof ProyectosFdcFontaneroRoute
  '/proyectos/icho': typeof ProyectosIchoRoute
  '/proyectos/solara': typeof ProyectosSolaraRoute
  '/proyectos/voltiarural': typeof ProyectosVoltiaruralRoute
  '/servicios/diseno-web': typeof ServiciosDisenoWebRoute
  '/servicios/seo': typeof ServiciosSeoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/proyectos/fdc-fontanero': typeof ProyectosFdcFontaneroRoute
  '/proyectos/icho': typeof ProyectosIchoRoute
  '/proyectos/solara': typeof ProyectosSolaraRoute
  '/proyectos/voltiarural': typeof ProyectosVoltiaruralRoute
  '/servicios/diseno-web': typeof ServiciosDisenoWebRoute
  '/servicios/seo': typeof ServiciosSeoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/proyectos/fdc-fontanero': typeof ProyectosFdcFontaneroRoute
  '/proyectos/icho': typeof ProyectosIchoRoute
  '/proyectos/solara': typeof ProyectosSolaraRoute
  '/proyectos/voltiarural': typeof ProyectosVoltiaruralRoute
  '/servicios/diseno-web': typeof ServiciosDisenoWebRoute
  '/servicios/seo': typeof ServiciosSeoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/nosotros'
    | '/proyectos/fdc-fontanero'
    | '/proyectos/icho'
    | '/proyectos/solara'
    | '/proyectos/voltiarural'
    | '/servicios/diseno-web'
    | '/servicios/seo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/nosotros'
    | '/proyectos/fdc-fontanero'
    | '/proyectos/icho'
    | '/proyectos/solara'
    | '/proyectos/voltiarural'
    | '/servicios/diseno-web'
    | '/servicios/seo'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/nosotros'
    | '/proyectos/fdc-fontanero'
    | '/proyectos/icho'
    | '/proyectos/solara'
    | '/proyectos/voltiarural'
    | '/servicios/diseno-web'
    | '/servicios/seo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  NosotrosRoute: typeof NosotrosRoute
  ProyectosFdcFontaneroRoute: typeof ProyectosFdcFontaneroRoute
  ProyectosIchoRoute: typeof ProyectosIchoRoute
  ProyectosSolaraRoute: typeof ProyectosSolaraRoute
  ProyectosVoltiaruralRoute: typeof ProyectosVoltiaruralRoute
  ServiciosDisenoWebRoute: typeof ServiciosDisenoWebRoute
  ServiciosSeoRoute: typeof ServiciosSeoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/seo': {
      id: '/servicios/seo'
      path: '/servicios/seo'
      fullPath: '/servicios/seo'
      preLoaderRoute: typeof ServiciosSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/diseno-web': {
      id: '/servicios/diseno-web'
      path: '/servicios/diseno-web'
      fullPath: '/servicios/diseno-web'
      preLoaderRoute: typeof ServiciosDisenoWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/voltiarural': {
      id: '/proyectos/voltiarural'
      path: '/proyectos/voltiarural'
      fullPath: '/proyectos/voltiarural'
      preLoaderRoute: typeof ProyectosVoltiaruralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/solara': {
      id: '/proyectos/solara'
      path: '/proyectos/solara'
      fullPath: '/proyectos/solara'
      preLoaderRoute: typeof ProyectosSolaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/icho': {
      id: '/proyectos/icho'
      path: '/proyectos/icho'
      fullPath: '/proyectos/icho'
      preLoaderRoute: typeof ProyectosIchoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/fdc-fontanero': {
      id: '/proyectos/fdc-fontanero'
      path: '/proyectos/fdc-fontanero'
      fullPath: '/proyectos/fdc-fontanero'
      preLoaderRoute: typeof ProyectosFdcFontaneroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  NosotrosRoute: NosotrosRoute,
  ProyectosFdcFontaneroRoute: ProyectosFdcFontaneroRoute,
  ProyectosIchoRoute: ProyectosIchoRoute,
  ProyectosSolaraRoute: ProyectosSolaraRoute,
  ProyectosVoltiaruralRoute: ProyectosVoltiaruralRoute,
  ServiciosDisenoWebRoute: ServiciosDisenoWebRoute,
  ServiciosSeoRoute: ServiciosSeoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
